train:
  suite: atari
  id: null
  action_repeat: 4
  grayscale: True
  all_actions: True
  time_limit: 108000
  time_penalty: 0.0
  precision: 32
test:
  suite: ${..train.suite}
  id: ${..train.id}
  action_repeat: ${..train.action_repeat}
  grayscale: ${..train.grayscale}
  all_actions: ${..train.all_actions}
  time_limit: ${..train.time_limit}
  time_penalty: ${..train.time_penalty}
  precision: ${..train.precision}

action_size: 18
max_steps: 1000
life_done: False